COUNTRIES = {
    "us": "United States",
    "ca": "Canada",
    "gb": "United Kingdom",
    "de": "Germany",
    "fr": "France",
    "es": "Spain",
    "it": "Italy",
    "ru": "Russia",
    "cn": "China",
    "br": "Brazil",
    "au": "Australia",
    "in": "India",
    "za": "South Africa",
    "ae": "United Arab Emirates",
    "eg": "Egypt",
    "mx": "Mexico",
    "ar": "Argentina",
    "be": "Belgium",
    "ch": "Switzerland",
    "nl": "Netherlands",
    "se": "Sweden",
    "no": "Norway",
    "dk": "Denmark",
    "at": "Austria",
    "pl": "Poland",
    "cz": "Czech Republic",
    "hu": "Hungary",
    "ro": "Romania",
    "gr": "Greece",
    "pt": "Portugal",
    "se": "Sweden",
    "fi": "Finland",
    "ie": "Ireland",
    "nz": "New Zealand",
    "sg": "Singapore",
    "hk": "Hong Kong",
    "tw": "Taiwan",
    "jp": "Japan",
    "kr": "South Korea",
    "th": "Thailand",
    "id": "Indonesia",
    "ph": "Philippines",
    "vn": "Vietnam",
    "my": "Malaysia",
    "tr": "Turkey",
    "il": "Israel",
    "sa": "Saudi Arabia",
    "ng": "Nigeria",
    "ke": "Kenya",
    "ma": "Morocco",
    "tn": "Tunisia",
    "dz": "Algeria",
    "ly": "Libya",
    "sd": "Sudan",
    "et": "Ethiopia",
    "gh": "Ghana",
    "sn": "Senegal",
    "ci": "Côte d'Ivoire",
    "cm": "Cameroon",
    "ug": "Uganda",
    "tz": "Tanzania",
    "zm": "Zambia",
    "zw": "Zimbabwe",
    "na": "Namibia",
    "bw": "Botswana",
    "mw": "Malawi",
    "ls": "Lesotho",
    "sz": "Eswatini",
    "mz": "Mozambique",
    "mg": "Madagascar",
    "mu": "Mauritius",
    "re": "Réunion",
    "sc": "Seychelles",
    "km": "Comoros",
    "cv": "Cape Verde",
    "gq": "Equatorial Guinea",
    "ga": "Gabon",
    "cg": "Congo",
    "cd": "Democratic Republic of the Congo",
    "ao": "Angola",
    "tg": "Togo",
    "bj": "Benin",
    "ne": "Niger",
    "td": "Chad",
    "cf": "Central African Republic",
    "dj": "Djibouti",
    "er": "Eritrea",
    "so": "Somalia",
    "iq": "Iraq",
    "sy": "Syria",
    "ir": "Iran",
    "af": "Afghanistan",
    "pk": "Pakistan",
    "bd": "Bangladesh",
    "mm": "Myanmar",
    "lk": "Sri Lanka",
    "np": "Nepal",
    "bt": "Bhutan",
    "mv": "Maldives",
    "kh": "Cambodia",
    "la": "Laos",
    "pg": "Papua New Guinea",
    "fj": "Fiji",
    "vu": "Vanuatu",
    "sb": "Solomon Islands",
    "nc": "New Caledonia",
    "pf": "French Polynesia",
    "gu": "Guam",
    "mp": "Northern Mariana Islands",
    "um": "United States Minor Outlying Islands",
    "pr": "Puerto Rico",
    "vi": "United States Virgin Islands",
    "aw": "Aruba",
    "an": "Netherlands Antilles",
    "ck": "Cook Islands",
    "nu": "Niue",
    "tk": "Tokelau",
    "wf": "Wallis and Futuna",
    "as": "American Samoa",
    "ws": "Samoa",
    "ki": "Kiribati",
    "tv": "Tuvalu",
    "nr": "Nauru",
    "mh": "Marshall Islands",
    "fm": "Federated States of Micronesia",
    "pw": "Palau",
    "ck": "Cook Islands",
    "nu": "Niue",
    "tk": "Tokelau",
    "wf": "Wallis and Futuna",
    "as": "American Samoa",
    "ws": "Samoa",
    "ki": "Kiribati",
    "tv": "Tuvalu",
    "nr": "Nauru",
    "mh": "Marshall Islands",
    "fm": "Federated States of Micronesia",
    "pw": "Palau"
}
